version: "3.13"

services:
  quality-check:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: >
      flake8 . --count --max-complexity=10 --max-line-length=88 --exclude=venv,migrations,__pycache__ &&
      pytest --cov=. --cov-report=term-missing --cov-fail-under=80

  web:
    build: .
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      quality-check:
        condition: service_completed_successfully
